paths:
  metadata: '/kaggle/working/metadata.pkl'
  output: '/kaggle/working'
  audio: '/kaggle/working/audio'
  aligned_metadata: '/kaggle/working/aligned_metadata.pkl'
  ljspeech_output: '/kaggle/working/ljspeech'


dataset:
  name: 'ghananlpcommunity/ghana-english-asr-2700hrs'
  target: 10000
